name: Flutter Unit Tests

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
      - run: flutter pub get
      - name: Create dummy .env file
        run: |
          mkdir -p assets
          echo "API_BASE_URL=https://dummy-url" > assets/.env
      - run: flutter test
