name: Flutter Unit Tests

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
      - run: flutter pub get
      - run: flutter test
